sudo: required
services:
  - docker

before_install:
  - docker build -t danielmmartin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true danielmmartin/react-test npm run test

after_success:
  - docker build -t danielmmartin/multi-client ./client
  - docker build -t danielmmartin/multi-nginx ./nginx
  - docker build -t danielmmartin/multi-worker ./worker
  - docker build -t danielmmartin/multi-server ./server
  # login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take these images and push them to docker hub
  - docker push danielmmartin/multi-client
  - docker push danielmmartin/multi-nginx
  - docker push danielmmartin/multi-worker
  - docker push danielmmartin/multi-server

